### ISSUE TITLE
Connections to Azure Postgres dbs raise `NIOSSLError.uncleanShutdown` on shutdown

### ISSUE THREAD

**Issue by finestructure** [vapor/postgres-nio#150] opened 2021-04-19 10:18 UTC
### Description

This is a follow-up to a [discussion on Discord](https://discord.com/channels/431917998102675485/448584561845338139/833567195849424956) where I first asked about the error and was advised to raise an issue.

We've recently switched the Swift Package Index' db from a non-SSL docker Postgres instance to Azure hosted Postgres, which uses SSL. Seemingly every command (Vapor.Command.run) that we're running in batch jobs is reporting

```
[ ERROR ] Channel error caught. Closing connection. [psql_connection_id: E70F3BE3-BBE1-4CD7-AE49-83DFF7877C13, psql_error: PSQLError(base: PostgresNIO.PSQLError.Base.connectionError(underlying: NIOSSL.NIOSSLError.uncleanShutdown))]
```

on shutdown.

This doesn't seem to affect operation except that it's really hard to diagnose issues with all the error noise.

It's not happening in the request loops of the webserver, so it seems to be an issue with Vapor.Command.run exiting uncleanly.

It only seems to be happening with Azure dbs. Running against a local dockerized PG db with SSL (same version, 11.6) does not exhibit the problem.

I've raised an issue with Azure to see if it's a config/server issue.

### To Reproduce

One example command that triggers the error is [here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/main/Sources/App/Commands/ReAnalyzeVersions.swift) but there's actually a stand-alone recipe to observe the error that I'm attaching as a playground.

It can also be re-created as follows:

Run [Arena](https://github.com/finestructure/Arena) to create a new playground with the required dependencies:

```
arena https://github.com/vapor/vapor https://github.com/vapor/fluent https://github.com/vapor/fluent-postgres-driver -o ssl-error-repro
```

and add:

```swift
import Vapor
import Fluent
import FluentPostgresDriver

final class Test: Model, Content {
    static let schema = "test"

    @ID(key: .id)
    var id: UUID?
}

func run() throws {
    let app = Application(.testing)
    defer { app.shutdown() }

    let tlsConfig: TLSConfiguration = .forClient()
    app.databases.use(.postgres(hostname: "pgnio-debug.postgres.database.azure.com",
                                port: 5432,
                                username: "test@pgnio-debug",
                                password: "<ask me for the password>",
                                database: "test",
                                tlsConfiguration: tlsConfig), as: .psql)

    let db = app.db

    let t = try Test.find(UUID("cafecafe-cafe-cafe-cafe-cafecafecafe"), on: db).wait()
    print("t: \(String(describing:  t))")
}

run()
```

When running, the console should print

```
t: Optional(Test(output: ["test_id": CAFECAFE-CAFE-CAFE-CAFE-CAFECAFECAFE]))
2021-04-19T12:05:25+0200 error codes.vapor.postgres : psql_connection_id=A8F4884F-DCB4-47CD-AB80-A48A3D320F00 psql_error=uncleanShutdown Channel error caught.
2021-04-19T12:05:25+0200 error codes.vapor.postgres : psql_connection_id=A8F4884F-DCB4-47CD-AB80-A48A3D320F00 psql_error=PSQLError(base: PostgresNIO.PSQLError.Base.connectionError(underlying: NIOSSL.NIOSSLError.uncleanShutdown)) Channel error caught. Closing connection.
```

And the expectation is that it _shouldn't_ 😆

**Comment by finestructure** [comment] 2021-04-19 10:20
[ssl-error-repro.zip](https://github.com/vapor/postgres-nio/files/6335194/ssl-error-repro.zip)

**Comment by gwynne** [comment] 2021-04-19 10:26
Paging @fabianfett as well

**Comment by finestructure** [comment] 2021-04-20 06:21
FYI, I've received a reply from Azure support:

> I checked the telemetry of your database everything seems to be fine. The type of error you are getting is most likely related to the Vapor layer or how it sets up the connection. 
>Postgres connections using TLS sometimes get closed after extended periods of inactivity. The next request handler that fetches such a connection from the connection pool will then fail with an NIOOpenSSL.OpenSSLError.uncleanShutdown error.

Highly unlikely, as the repro case runs within a second or less.
 
> From the Database side, you can also try to configure parameters pstatement_timeout and idle_in_transaction_session_timeout. Please, check whether these are equal in your docker implementation. 
As a reference, check this article. [Tracking and managing your Postgres connections - Craig Kerstiens](https://www.craigkerstiens.com/2017/09/18/postgres-connection-management/). 

> From the Vapor/Swift side, please try to use 'ignoreUncleanShutdown = true' and see with the error is bypassed by the interface. 

I'm not sure what `ignoreUncleanShutdown` they're referring to - it's not a Postgres setting as far as I can see. I'll follow up to ask. Maybe they're just speculating there might be a flag like that in PostgresNIO.
 
> More on the connection management topic for Application Layer: [Troubleshoot PostgreSQL: ‘An existing connection was forcibly closed by the remote host’ - Microsoft Tech Community](https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/troubleshoot-postgresql-an-existing-connection-was-forcibly/ba-p/925164)

**Comment by finestructure** [comment] 2021-04-20 09:14
I'm attaching the config (`SHOW ALL;`) of the two dbs I've tested this repro with:

- dockerised 11.6 with SSL (no error)
- Azure 11.6 (SSLError)

Nothing jumps out at me but I'm also not really sure what to look for.

The timeout values seem to be the same or of longer values than the test runs. `deadlock_timeout` is 1s but that's both probably longer than the query runs effectively (the test runs in ~1.5s for me but that's in a playground, so slower + network latency) and doesn't really sound like a likely candidate.

[docker-db-config.csv](https://github.com/vapor/postgres-nio/files/6342217/docker-db-config.csv)
[azure-db-config.csv](https://github.com/vapor/postgres-nio/files/6342218/azure-db-config.csv)

**Comment by fabianfett** [comment] 2021-04-20 10:25
@finestructure Thanks for your investigations. Would you mind reproducing the error with trace level logging (Be prepared it will log a lot!)? And uploading the logs. Please make sure that you remove all sensitive data before upload.

**Comment by finestructure** [comment] 2021-04-20 11:32
Thanks for taking a look, @fabianfett ! Here you go:

```
2021-04-20T13:30:56+0200 debug codes.vapor.application : database-id=psql query read test filters=[test[id] = CAFECAFE-CAFE-CAFE-CAFE-CAFECAFECAFE] limits=[count(1)]
2021-04-20T13:30:56+0200 debug codes.vapor.application : database-id=psql No available connections on this event loop, creating a new one
2021-04-20T13:30:58+0200 trace codes.vapor.application : database-id=psql Releasing connection
2021-04-20T13:30:58+0200 debug codes.vapor.application : Application shutting down
2021-04-20T13:30:58+0200 trace codes.vapor.application : Shutting down providers
2021-04-20T13:30:58+0200 error codes.vapor.postgres : psql_connection_id=B445610B-1D5B-4C40-BACB-1EABDA28A99E psql_error=uncleanShutdown Channel error caught.
2021-04-20T13:30:58+0200 error codes.vapor.postgres : psql_connection_id=B445610B-1D5B-4C40-BACB-1EABDA28A99E psql_error=PSQLError(base: PostgresNIO.PSQLError.Base.connectionError(underlying: NIOSSL.NIOSSLError.uncleanShutdown)) Channel error caught. Closing connection.
2021-04-20T13:30:58+0200 trace codes.vapor.application : Clearing Application storage
2021-04-20T13:30:58+0200 trace codes.vapor.application : Shutting down EventLoopGroup
2021-04-20T13:30:58+0200 trace codes.vapor.application : Application shutdown complete
2021-04-20T13:30:58+0200 trace codes.vapor.application : Application deinitialized, goodbye!
elapsed: 1.5916249752044678
```

**Comment by fabianfett** [comment] 2021-04-21 07:55
@finestructure Thank you. Sadly though, those are only trace logs from the connection pool. It seems to me like the log level is not propagated to every single connection in the pool. 😔

Could you please reproduce the problem with a single connection? By connecting to the database with

https://github.com/vapor/postgres-nio/blob/d97f26858003d87a1d2b52c0061b243035620996/Sources/PostgresNIO/Connection/PostgresConnection%2BConnect.swift#L3-L10

Please not that you have to manually do the authentication afterwards:

https://github.com/vapor/postgres-nio/blob/d97f26858003d87a1d2b52c0061b243035620996/Sources/PostgresNIO/Connection/PostgresConnection%2BAuthenticate.swift#L3-L9

Full example can be this:

https://github.com/vapor/postgres-nio/blob/d97f26858003d87a1d2b52c0061b243035620996/Tests/PostgresNIOTests/PostgresNIOTests.swift#L676-L696

I'm well aware that those APIs are not ideal to deal with and we already have "cleaner" alternatives prepared. However those have not been made public yet.

**Comment by finestructure** [comment] 2021-04-21 08:14
Sure, here you go!

```
func run() throws {
    let app = Application(.testing)
    defer { app.shutdown() }
    app.logger.logLevel = .trace

    let conn = try PostgresConnection.connect(
        to: SocketAddress.makeAddressResolvingHost("pgnio-debug.postgres.database.azure.com", port: 5432),
        tlsConfiguration: .forClient(certificateVerification: .none),
        serverHostname: "pgnio-debug.postgres.database.azure.com",
        on: app.eventLoopGroup.next()
    ).wait()

    try conn.authenticate(
        username: "test@pgnio-debug",
        database: "test",
        password: "<ask me for the password>"
    ).wait()

    defer { try? conn.close().wait() }

    let _ = try conn.simpleQuery("SELECT * from test").wait()
}

let start = Date()
run()
print("elapsed: \(Date().timeIntervalSince(start))")
```

Output:

```
2021-04-21T10:12:15+0200 error codes.vapor.postgres : psql_connection_id=F055E819-8373-4029-8CFB-204D82FC47E9 psql_error=uncleanShutdown Channel error caught.
2021-04-21T10:12:15+0200 error codes.vapor.postgres : psql_connection_id=F055E819-8373-4029-8CFB-204D82FC47E9 psql_error=PSQLError(base: PostgresNIO.PSQLError.Base.connectionError(underlying: NIOSSL.NIOSSLError.uncleanShutdown)) Channel error caught. Closing connection.
2021-04-21T10:12:15+0200 debug codes.vapor.application : Application shutting down
2021-04-21T10:12:15+0200 trace codes.vapor.application : Shutting down providers
2021-04-21T10:12:15+0200 trace codes.vapor.application : Clearing Application storage
2021-04-21T10:12:15+0200 trace codes.vapor.application : Shutting down EventLoopGroup
2021-04-21T10:12:15+0200 trace codes.vapor.application : Application shutdown complete
2021-04-21T10:12:15+0200 trace codes.vapor.application : Application deinitialized, goodbye!
elapsed: 1.9744360446929932
```

**Comment by finestructure** [comment] 2021-04-21 08:14
Whoops, forgot to set the trace - hold on.

**Comment by finestructure** [comment] 2021-04-21 08:17
Updated

**Comment by fabianfett** [comment] 2021-04-21 08:18
I'm afraid you leaked passwords :(

**Comment by finestructure** [comment] 2021-04-21 08:19
Yeah, but it's not a problem - feel free to try this. It's a db that I set up purely for this test :)

**Comment by finestructure** [comment] 2021-04-21 08:19
(It'd probably be good if trace masked these though)

**Comment by fabianfett** [comment] 2021-04-21 09:17
Okay, long story short: 

There are two issues at hand here:

1. If the StateMachine is in state `.closing` it doesn't need to issue a `.closeConnectionAndCleanup`. Everything has already been cleaned up (otherwise we wouldn't be in `.closing`) and a connection close has also already been issued. Instead it should keep its cool and just ignore the error. 😎
2. We should revise our logging to be inline with the [swift-server recommendations](https://github.com/swift-server/guides/blob/main/log-levels.md)

I'll have a pr up for 1 shortly and hope to have some time over the weekend for 2.

Server hint – since I have just seen it in the example code: To make use of the certificate validation (currently disabled with `certificateVerification: .none`) just install the azure certificate on your machine (or docker image):

https://docs.microsoft.com/en-us/azure/postgresql/concepts-ssl-connection-security

**Comment by finestructure** [comment] 2021-04-21 09:20
That's great, thanks again for taking a look and finding the root cause so quickly!

> Service hint – since I have just seen it in the example code: To make use of the certificate validation (currently disabled with `certificateVerification: .none`) just install the azure certificate on your machine (or docker image):

Ah yes, this was just a relic from testing with a local dockerised Postgres with TLS that I forgot to switch back. It's not how we're connecting to our Azure instances :)

**Closed** 2021-04-21 13:44 UTC
Labels: bug
